"""empty message

<<<<<<<< HEAD:migrations/versions/697068c25744_.py
Revision ID: 697068c25744
Revises: 
Create Date: 2024-03-06 20:08:36.043240
========
Revision ID: 97700f2517a4
Revises: 
Create Date: 2024-03-07 15:29:47.617310
>>>>>>>> 9fa049a219a875aec9d6f27897cda037cfbd258f:migrations/versions/97700f2517a4_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/697068c25744_.py
revision = '697068c25744'
========
revision = '97700f2517a4'
>>>>>>>> 9fa049a219a875aec9d6f27897cda037cfbd258f:migrations/versions/97700f2517a4_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
