"""empty message

Revision ID: c3827bf2cfd5
Revises: a751f51929b7
Create Date: 2024-03-08 11:29:11.407790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3827bf2cfd5'
down_revision = 'a751f51929b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint('pedido_id_mesa_fkey', type_='foreignkey')
        batch_op.drop_constraint('pedido_id_cliente_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mesa', ['id_mesa'], ['id'])
        batch_op.create_foreign_key(None, 'cliente', ['id_cliente'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pedido_id_cliente_fkey', 'producto', ['id_cliente'], ['id'])
        batch_op.create_foreign_key('pedido_id_mesa_fkey', 'pedido', ['id_mesa'], ['id'])

    # ### end Alembic commands ###
