"""empty message

<<<<<<<< HEAD:migrations/versions/fe0ced9248f0_.py
Revision ID: fe0ced9248f0
Revises: 
Create Date: 2024-03-13 20:03:17.819318
========
Revision ID: d584b9531dc8
Revises: 
Create Date: 2024-03-13 16:09:39.052602
>>>>>>>> 1cf83a2fd7019556e50de560c531dcd24577266a:migrations/versions/d584b9531dc8_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/fe0ced9248f0_.py
revision = 'fe0ced9248f0'
========
revision = 'd584b9531dc8'
>>>>>>>> 1cf83a2fd7019556e50de560c531dcd24577266a:migrations/versions/d584b9531dc8_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camarero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mesa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_camarero', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id_camarero'], ['camarero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_menu', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_menu'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_mesa', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=80), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['id_mesa'], ['mesa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=80), nullable=False),
    sa.Column('metodo', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Preparando', 'Listo', 'Servido', name='status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto_pedido')
    op.drop_table('pago')
    op.drop_table('pedido')
    op.drop_table('producto')
    op.drop_table('mesa')
    op.drop_table('user')
    op.drop_table('menu')
    op.drop_table('user')
    op.drop_table('cliente')
    op.drop_table('camarero')
    # ### end Alembic commands ###
